engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  shellcheck:
    enabled: true
ratings:
  paths:
    - src/**/*.js
    - src/**/*.es6
    - src/bin/cpm
