engines:
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
        - .js
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          extensions:
            - .es6
            - .js
  shellcheck:
    enabled: true
ratings:
  paths:
    - src/**/*.js
    - src/**/*.es6
    - src/bin/cpm
