language: node_js
node_js:
  - 4.4.0
cache:
  directories:
    - node_modules
sudo: required

before_script:
 - sudo $(which chmod) 777 ./dist/bin/cpm
 - sudo $(which chown) $(whoami) ./dist/bin/cpm
script: sudo $(which npm) test
