language: node_js
node_js:
  - 4.4.0
cache:
  directories:
    - node_modules
sudo: required

before_script:
 - sudo chmod a+x ./dist/bin/cpm
 - sudo chmod a+x ./dist/bin/cpm-cli.js
script: sudo $(which npm) test
