language: node_js
node_js:
 - 4.4.0
cache:
  directories:
    - node_modules
sudo: required

install:
  - npm install codecov
  - npm install codeclimate-test-reporter
before_script:
  - grunt install --alias
after_script:
  - istanbul cover test/cli.test.js
  - codeclimate-test-reporter < coverage/lcov.info
  - cat ./coverage/coverage.json | codecov
addons:
  code_climate:
    repo_token:
      secure: "g65TAts95ugfFgb88PkKI8tJiAG775TZzTMrdpQqGf1Wx1QGGeWY+vdMgHMYQq6nQBxQhYRY7v3049MzCfHy7a3HEI/8AbCpZf0wEfoZnBfXSW0WndA/ZB8Z2ColzXdGbyY+DNwpf61MImPVHTrP2zfONz2Ju9tAFQLjkwOFNRcNPEdvkEwOGLT3TCdoYY5meMdJT2sTeT8ZeCuHHE5We8b9KRvOSyJA+UEdgqdTNtcxJlJREimob9mauv/UtXmpaiRYsWK+cK/oHTWIk/TAVbHrmkJiuEHc70QC4wPGmkjKBGV3LVQWefWJFjCWuJTXB3rOaaA9f9+woRo7TmTnDJNHVa3QRxmr58fTyWra43aqfKz549JLUjPTNrn82q2LNz1zlK3WJYJWtntBSSAvxQgAKxJfCxGg2FK7Qui2t7+m0zkexumgZnaFGTgKo3xOdCw0lLyB3MSvmDXMqK5kkxsQZNfwBpcwDaHMMJKg1QzlNoUtvFuFg9KjgC4fcwByqcsAqdEFw8F32u1dwSNwapZYMsiux32Kk/B8wsV212JlgGGnkcNG7Aiioyug4GLUTIfjpRI9aL+qseLq+Xgg84Q7gtQHbMKUSr4CfwsG2vVW3xcHHoKTdOkxXTTMDmeqrM87zXaPuwMqRtE72OUH/c++DUXZKEwDnItGBxsjTA8="
