language: node_js
node_js:
  - 4.4.0
cache:
  directories:
    - node_modules
sudo: required

before_script:
 - sudo chmod 777 ./dist/bin/cpm
 - sudo chmod 777 ./dist/bin/cpm-cli.js
 - ls -l ./dist/bin
script: sudo $(which npm) test
