language: node_js
node_js:
  - 4.4.0
cache:
  directories:
    - node_modules
sudo: required

before_script:
 - grunt install --alias
addons:
    code_climate:
        repo_token: ENV['CODE_CLIMATE_TOKEN']
